### ISSUE TITLE
Fix error: pollyfil `crypto.getRandomValues()`

### ISSUE THREAD

**Issue by emadbaqeri** [krzysztof-tys/tweak-your-system#22]

**Comment by krzysztof-tys** [comment]
PR merged, feel free to close the issue

**Comment by emadbaqeri** [comment]
closing this one since fixed on the PR #23

**Comment by emadbaqeri** [comment]
closing this one since fixed on the PR https://github.com/krzysztof-tys/tweak-your-system/pull/23
